# Generated by Django 4.1.3 on 2023-08-05 12:25

import billing.models
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('price', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Add Ons',
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Historical Bills',
            },
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash', models.IntegerField(default=0, verbose_name='Cash In Hand')),
            ],
        ),
        migrations.CreateModel(
            name='CashInflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('-date',),
            },
        ),
        migrations.CreateModel(
            name='CashOutflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=250)),
                ('month', models.PositiveIntegerField(default=8)),
                ('year', models.PositiveIntegerField(default=2023)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date_cleared', models.DateField(blank=True, default=datetime.date(2023, 8, 5), null=True)),
            ],
            options={
                'ordering': ('year', 'month', 'date_cleared'),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('H', 'Holud'), ('M', 'Mehedi'), ('E', 'Engagement'), ('A', 'Akdh'), ('WE', 'Wedding'), ('WA', 'Walima'), ('BS', 'Bridal Shower'), ('BD', 'Birthday'), ('O', 'Others')], max_length=250)),
                ('date', models.DateField()),
                ('venue', models.CharField(max_length=200)),
                ('event_status', models.CharField(choices=[('PR', 'Prospective'), ('C', 'Confirmed'), ('D', 'Completed'), ('S', 'SHELVED')], default='PR', editable=False, max_length=100)),
                ('payment_received', models.IntegerField(default=0, editable=False)),
                ('discount', models.PositiveIntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('N', 'None'), ('P', 'Partial'), ('F', 'Full')], default='N', editable=False, max_length=50)),
                ('add_ons', models.ManyToManyField(blank=True, related_name='event', to='billing.addon', verbose_name='Add Ons')),
                ('client', models.ForeignKey(default=billing.models.Client.get_latest_pk, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event', to='billing.client')),
                ('lead_photographers', models.ManyToManyField(blank=True, to='user.teammember', verbose_name='Event Lead(s)')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('active', models.BooleanField(default=True)),
                ('details', models.CharField(default='200 4R, 30 6L, 3 8R prints', max_length=250)),
                ('coverage', models.CharField(choices=[('V', 'Venue Only'), ('BV', 'Before + Venue'), ('BVA', 'Before + Venue + After')], max_length=250)),
                ('budget', models.PositiveIntegerField(default=0, editable=False)),
                ('num_photographer', models.PositiveIntegerField(default=0)),
                ('num_cinematographer', models.PositiveIntegerField(default=0)),
                ('time', models.IntegerField(default=5)),
            ],
            options={
                'verbose_name_plural': 'Event Packages',
            },
        ),
        migrations.CreateModel(
            name='TeamMemberBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField(default=7)),
                ('year', models.PositiveIntegerField(default=2023)),
                ('adjustment', models.IntegerField(default=0)),
                ('comment', models.CharField(blank=True, max_length=1000)),
                ('events', models.ManyToManyField(related_name='photographer', to='billing.event')),
                ('team_member', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='user.teammember')),
            ],
            options={
                'verbose_name_plural': 'Team member bills',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dates', models.TextField()),
                ('discount', models.IntegerField(default=0)),
                ('quantity', models.IntegerField(default=0)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='billing.bill')),
                ('leads', models.ManyToManyField(blank=True, to='user.teammember')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.package')),
            ],
        ),
        migrations.CreateModel(
            name='OutflowToTeamMemberBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('month', models.PositiveIntegerField(default=8)),
                ('year', models.PositiveIntegerField(default=2023)),
                ('cleared_amount', models.IntegerField(default=0)),
                ('cash_outflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.cashoutflow')),
                ('team_member_bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.teammemberbill')),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('end_balance', models.IntegerField(default=0, editable=False)),
                ('revenue', models.IntegerField(default=0)),
                ('cogs', models.IntegerField(default=0, verbose_name='Cost of Human Resource')),
                ('expenses', models.IntegerField(default=0, verbose_name='Overhead Expenses')),
                ('advance_received', models.IntegerField(default=0)),
                ('month', models.PositiveIntegerField(default=8, editable=False)),
                ('year', models.PositiveIntegerField(default=2023, editable=False)),
                ('cash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.cash')),
            ],
            options={
                'ordering': ('year', 'month'),
            },
        ),
        migrations.CreateModel(
            name='InflowToEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.event')),
                ('inflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.cashinflow')),
            ],
        ),
        migrations.CreateModel(
            name='InflowToBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.bill')),
                ('inflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.cashinflow')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.package'),
        ),
        migrations.CreateModel(
            name='CustomPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField()),
                ('date', models.TextField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_purchase', to='billing.bill')),
                ('leads', models.ManyToManyField(blank=True, to='user.teammember')),
            ],
        ),
        migrations.AddField(
            model_name='cashinflow',
            name='source',
            field=models.ForeignKey(default=billing.models.Client.get_latest_pk, on_delete=django.db.models.deletion.CASCADE, to='billing.client'),
        ),
        migrations.AddField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill', to='billing.client'),
        ),
        migrations.AddField(
            model_name='bill',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AddOnPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('add_on', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.addon')),
                ('bill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='add_ons', to='billing.bill')),
            ],
        ),
    ]
