# Generated by Django 4.1.3 on 2024-01-22 11:42

import billing.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_cashoutflow_date_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonpurchase',
            name='add_on',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.addon'),
        ),
        migrations.AlterField(
            model_name='addonpurchase',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='add_ons', to='billing.bill'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill', to='billing.client'),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='date_cleared',
            field=models.DateField(blank=True, default=datetime.date(2024, 1, 22), null=True),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='month',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='custompurchase',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_purchase', to='billing.bill'),
        ),
        migrations.AlterField(
            model_name='event',
            name='client',
            field=models.ForeignKey(default=billing.models.Client.get_latest_pk, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='billing.client'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('H', 'Holud'), ('M', 'Mehedi'), ('E', 'Engagement'), ('A', 'Akdh'), ('WE', 'Wedding'), ('WA', 'Walima'), ('BS', 'Bridal Shower'), ('BD', 'Birthday'), ('N', 'Nikkah'), ('AB', 'Aiburo Bhaat'), ('S', 'Sangeet'), ('B', 'Biye'), ('BB', 'Basibiye'), ('BY', 'Biday'), ('WR', 'Wedding Reception'), ('R', 'Reception'), ('BT', 'Bostralongkar'), ('DM', 'Dodhimangal'), ('FGT', 'Family Get Together'), ('AV', 'Anniversary'), ('CS', 'Couple Shoot'), ('CE', 'Corporate Event'), ('FP', 'Family Photography'), ('PE', 'Proposal Event'), ('DE', 'Dala Exchange'), ('O', 'Others')], max_length=250),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='month',
            field=models.PositiveIntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='year',
            field=models.PositiveIntegerField(default=2024, editable=False),
        ),
        migrations.AlterField(
            model_name='outflowtoteammemberbill',
            name='month',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='outflowtoteammemberbill',
            name='year',
            field=models.PositiveIntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='package',
            name='budget',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase', to='billing.bill'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.package'),
        ),
        migrations.AlterField(
            model_name='teammemberbill',
            name='month',
            field=models.PositiveIntegerField(default=12),
        ),
    ]
