# Generated by Django 4.1.3 on 2024-01-23 15:13

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_addonpurchase_add_on_alter_addonpurchase_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cashoutflow',
            name='date_cleared',
            field=models.DateField(blank=True, default=datetime.date(2024, 1, 23), null=True),
        ),
    ]
