# Generated by Django 4.1.3 on 2024-01-25 09:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_client_date_added_alter_cashoutflow_date_cleared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashoutflow',
            name='date_cleared',
            field=models.DateField(blank=True, default=datetime.date(2024, 1, 25), null=True),
        ),
        migrations.AlterField(
            model_name='package',
            name='budget',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
