# Generated by Django 4.1.3 on 2024-01-25 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_cashoutflow_date_cleared_alter_package_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='budget',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
